port: 9123
requestTimeout: 5s
scrapeInterval: 60s
devices:
  - IPAddress: "192.168.66.151"
    displayName: "Office"
    type: "1pm"
  - IPAddress: "192.168.66.154"
    displayName: "Lounge"
    type: "2pm"
    channelNames:
      0: "LeftBlind"
      1: "RightBlind"
  - IPAddress: "192.168.66.164"
    displayName: "Bedroom"
    type: "2pmgen3"
    channelNames:
      0: "Plugs"
      1: "Heater"
