port: 9123
requestTimeout: 8s
scrapeInterval: 10s
devices:
  - IPAddress: dining-room-plugs.int.stangl.co.za
    displayName: DiningRoom
    type: 2pmPlus
    generation: 2
    channelNames:
      0: "Double-Plugs"
      1: "Shelf"
  - IPAddress: family-room-plug.int.stangl.co.za
    displayName: FamilyRoomPlug
    type: 1pmPlus
    generation: 2
  - IPAddress: family-room-lights.int.stangl.co.za
    displayName: FamilyRoomLights
    type: dimmer2
  - IPAddress: fridge-plug.int.stangl.co.za
    displayName: Fridge
    type: 1pmPlus
    generation: 2
  - IPAddress: gas-geyser.int.stangl.co.za
    displayName: GasGeyser
    type: 1pm
  - IPAddress: jax-bedroom-plug.int.stangl.co.za
    displayName: JaxBedroom
    type: 1pm
  - IPAddress: jax-desk-psu.int.stangl.co.za
    displayName: JaxDeskPSU
    type: 1pm
  - IPAddress: kitchen-appliances.int.stangl.co.za
    displayName: KitchenAppliances
    type: 1pm
  - IPAddress: kitchen-counter-plug.int.stangl.co.za
    displayName: KitchenCounter
    type: 1pmPlus
  - IPAddress: lounge-plugs.int.stangl.co.za
    displayName: LoungePlug
    type: 2pmPlus
    generation: 2
    channelNames:
      0: "Double-Plugs"
      1: "Extention"
  - IPAddress: lounge-extra-plug.int.stangl.co.za
    displayName: LoungeExtraPlug
    type: 1pm
  - IPAddress: maids-room-plug.int.stangl.co.za
    displayName: MaidsRoom
    type: 1pmPlus
    generation: 2
  - IPAddress: main-bedroom-plugs.int.stangl.co.za
    displayName: MainBedroom
    type: 2pmgen3
    generation: 3
    channelNames:
      0: "Plugs"
      1: "Heater"
  - IPAddress: office-hvac-plugs.int.stangl.co.za
    displayName: Office-HVAC
    type: 2pmgen3
    generation: 3
    channelNames:
      0: Aircon
      1: UnderCarpet-Heater
  - IPAddress: main-bedroom-psu.int.stangl.co.za
    displayName: BedroomPSU
    type: 1pmPlus
    generation: 2
  - IPAddress: main-db-em.int.stangl.co.za
    displayName: MainDB
    type: em
  - IPAddress: network-cabinet-psu.int.stangl.co.za
    displayName: NetworkCabinetPSU
    type: 1pmPlus
    generation: 2
  - IPAddress: office-plug.int.stangl.co.za
    displayName: OfficePlug
    type: 1pmPlus
    generation: 2
  - IPAddress: office-screen.int.stangl.co.za
    displayName: Office-Screen
    type: 1pm
  - IPAddress: spare-room-plug.int.stangl.co.za
    displayName: SpareRoomPlug
    type: 1pmPlus
    generation: 2
  - IPAddress: work-desk-psu.int.stangl.co.za
    displayName: WorkDeskPSU
    type: 1pmPlus
    generation: 2
