port: 9123
requestTimeout: 5s
scrapeInterval: 60s
devices:
  - IPAddress: "192.168.88.38"
    displayName: "OfficePlug"
    type: "1pm"
  - IPAddress: "192.168.88.39"
    displayName: "FamilyRoom2PM"
    type: "2pm"
    channelNames:
      0: "LeftBlind"
      1: "RightBlind"